#' Trio-specific null distributions by forward and backward simulation
#'
#' Builds the reference distribution of the LOD score for a *true* parent,
#' conditioned on the genotypes actually observed in the case being tested,
#' following the pairwise simulation scheme of Amiri Roudbar et al. (2025).
#'
#' The motivation is that the alleles carried by a particular candidate and
#' offspring, and the particular pattern of missing data, change the
#' distribution of the statistic. A single population-wide criterion, as used by
#' the classical approach of Marshall et al. (1998), therefore applies an
#' average threshold to cases that are not exchangeable.
#'
#' @section Forward simulation:
#' Used for a **paternity test**: is this specific candidate the parent? The
#' candidate's observed genotype is held fixed, as is the known parent's if one
#' is supplied. An offspring genotype is generated by Mendelian sampling of one
#' allele from the candidate and one from the known parent, or from population
#' allele frequencies where the second parent is unknown. Genotyping error and
#' missing data are then applied to the simulated offspring, and the candidate's
#' LOD score is computed. The resulting distribution is that of the LOD score
#' when the candidate genuinely is the parent.
#'
#' @section Backward simulation:
#' Used for an **assignment test**: which candidate is the parent? The
#' offspring's observed genotype is held fixed. A random true parent is built by
#' sampling his first allele from the offspring's alleles - excluding the allele
#' traceable to the known parent, where the known parent makes it traceable - and
#' his second allele from population allele frequencies. Genotyping error and
#' missing data are applied to the simulated parent before the LOD score is
#' computed. The resulting distribution is that of the LOD score over the true
#' parents compatible with this offspring.
#'
#' Because both distributions describe true parents, the decision rule is a
#' **lower** tail: see [lod_critical()].
#'
#' @param g A `"genotypes"` object.
#' @param offspring Identifier of the offspring. Required for
#'   `method = "backward"`; used for the missing-data pattern when
#'   `method = "forward"` and supplied.
#' @param candidate Identifier of the candidate parent. Required for
#'   `method = "forward"`.
#' @param freqs An `"allele_freqs"` object.
#' @param error Genotyping error rate, one value or one per locus.
#' @param known Identifier of the known second parent, or `NULL`.
#' @param method `"forward"` or `"backward"`.
#' @param nsim Number of simulation replicates. Amiri Roudbar et al. (2025) use
#'   10000.
#' @param prop_typed Probability that a simulated genotype is scored. Defaults
#'   to the observed proportion of typed loci in the fixed individual.
#' @param type Parentage configuration, as in [parentage_lod()]. `"one_known"`
#'   is implied when `known` is supplied.
#'
#' @return A numeric vector of `nsim` simulated LOD scores, of class
#'   `"lod_null"`, carrying the simulation settings as attributes.
#'
#' @references
#' Amiri Roudbar, M., Mousavi, S.F., Akbarzadeh, M., Brounts, S.H. & Momen, M.
#' (2025) Pairwise paternity assignment with forward-backward simulations:
#' refining CERVUS using trio-based likelihood and locus-specific error rates.
#' \emph{Ecology and Evolution}, \strong{15}(10), e72230.
#' \doi{10.1002/ece3.72230}
#'
#' Marshall, T.C., Slate, J., Kruuk, L.E.B. & Pemberton, J.M. (1998)
#' Statistical confidence for likelihood-based paternity inference in natural
#' populations. \emph{Molecular Ecology}, \strong{7}, 639--655.
#' \doi{10.1046/j.1365-294x.1998.00374.x}
#'
#' @examples
#' sim <- simulate_population(n = 30, n_loci = 8, n_alleles = 6, seed = 3)
#' p <- allele_freqs(sim$genotypes)
#' nd <- lod_null(sim$genotypes, offspring = sim$pedigree$offspring[1],
#'                candidate = sim$pedigree$sire[1], freqs = p, error = 0.01,
#'                method = "forward", nsim = 500)
#' lod_critical(nd)
#' @export
lod_null <- function(g, offspring = NULL, candidate = NULL, freqs, error,
                     known = NULL, method = c("forward", "backward"),
                     nsim = 10000L, prop_typed = NULL,
                     type = c("both_unknown", "one_known")) {
  stopifnot(inherits(g, "genotypes"))
  method <- match.arg(method)
  type <- if (!is.null(known)) "one_known" else match.arg(type)
  if (type == "one_known" && is.null(known)) {
    stop("`known` must be supplied for type = 'one_known'.", call. = FALSE)
  }
  .check_freqs(freqs, g)
  nl <- n_loci(g)
  e <- .expand_error(error, nl)
  nsim <- as.integer(nsim)
  if (nsim < 1L) stop("`nsim` must be at least 1.", call. = FALSE)

  kn <- if (is.null(known)) NULL else .row_of(g, known, "known parent")

  if (method == "forward") {
    if (is.null(candidate)) stop("`candidate` is required for forward simulation.", call. = FALSE)
    cg <- .row_of(g, candidate, "candidate")
    if (is.null(prop_typed)) {
      prop_typed <- if (!is.null(offspring)) mean(!is.na(.row_of(g, offspring, "offspring")$a1))
                    else mean(!is.na(cg$a1))
    }
    lod <- .sim_forward(cg, kn, freqs, e, nsim, prop_typed, type)
  } else {
    if (is.null(offspring)) stop("`offspring` is required for backward simulation.", call. = FALSE)
    og <- .row_of(g, offspring, "offspring")
    if (is.null(prop_typed)) {
      prop_typed <- if (!is.null(candidate)) mean(!is.na(.row_of(g, candidate, "candidate")$a1))
                    else mean(!is.na(og$a1))
    }
    lod <- .sim_backward(og, kn, freqs, e, nsim, prop_typed, type)
  }
  structure(lod, class = c("lod_null", "numeric"), method = method,
            type = type, nsim = nsim, error = e, prop_typed = prop_typed)
}

# Forward: candidate (and known parent) fixed; simulate the offspring.
.sim_forward <- function(cg, kn, freqs, e, nsim, prop_typed, type) {
  nl <- length(freqs)
  tot <- numeric(nsim)
  for (l in seq_len(nl)) {
    c1 <- cg$a1[l]; c2 <- cg$a2[l]
    k1 <- if (is.null(kn)) NA_integer_ else kn$a1[l]
    k2 <- if (is.null(kn)) NA_integer_ else kn$a2[l]
    if (is.na(c1) || (type == "one_known" && is.na(k1))) next
    p <- freqs[[l]]
    from_c <- .pick2(c1, c2, nsim)
    from_o <- if (type == "one_known") .pick2(k1, k2, nsim)
              else sample.int(length(p), nsim, TRUE, prob = p)
    o <- .apply_error(from_c, from_o, e[l], p)
    o <- .apply_missing(o, prop_typed)
    v <- lod_locus(o$a1, o$a2, c1, c2, p = p, error = e[l],
                   k1 = k1, k2 = k2, type = type)
    v[!is.finite(v)] <- 0
    tot <- tot + v
  }
  tot
}

# Backward: offspring (and known parent) fixed; simulate the true parent.
.sim_backward <- function(og, kn, freqs, e, nsim, prop_typed, type) {
  nl <- length(freqs)
  tot <- numeric(nsim)
  for (l in seq_len(nl)) {
    o1 <- og$a1[l]; o2 <- og$a2[l]
    k1 <- if (is.null(kn)) NA_integer_ else kn$a1[l]
    k2 <- if (is.null(kn)) NA_integer_ else kn$a2[l]
    if (is.na(o1) || (type == "one_known" && is.na(k1))) next
    p <- freqs[[l]]
    opts <- if (type == "one_known") .paternal_options(o1, o2, k1, k2) else c(o1, o2)
    from_o <- if (length(opts) == 1L) rep(opts, nsim) else .pick2(opts[1L], opts[2L], nsim)
    from_p <- sample.int(length(p), nsim, TRUE, prob = p)
    cand <- .apply_error(from_o, from_p, e[l], p)
    cand <- .apply_missing(cand, prop_typed)
    v <- lod_locus(o1, o2, cand$a1, cand$a2, p = p, error = e[l],
                   k1 = k1, k2 = k2, type = type)
    v[!is.finite(v)] <- 0
    tot <- tot + v
  }
  tot
}

# Offspring alleles that could have come from the father, given the mother.
.paternal_options <- function(o1, o2, k1, k2) {
  opts <- integer(0)
  if (o1 %in% c(k1, k2)) opts <- c(opts, o2)
  if (o2 %in% c(k1, k2)) opts <- c(opts, o1)
  if (length(opts) == 0L) opts <- c(o1, o2)   # incompatible: fall back to either
  unique(opts)
}

.pick2 <- function(a, b, n) if (a == b) rep(a, n) else ifelse(stats::runif(n) < 0.5, a, b)

.apply_error <- function(a1, a2, e, p) {
  n <- length(a1)
  if (e > 0) {
    hit <- stats::runif(n) < e
    m <- sum(hit)
    if (m > 0) {
      a1[hit] <- sample.int(length(p), m, TRUE, prob = p)
      a2[hit] <- sample.int(length(p), m, TRUE, prob = p)
    }
  }
  list(a1 = a1, a2 = a2)
}

.apply_missing <- function(x, prop_typed) {
  if (prop_typed < 1) {
    gone <- stats::runif(length(x$a1)) >= prop_typed
    x$a1[gone] <- NA_integer_
    x$a2[gone] <- NA_integer_
  }
  x
}

#' Critical LOD values from a trio-specific null distribution
#'
#' Converts a simulated true-parent LOD distribution from [lod_null()] into
#' decision thresholds. Because the distribution describes parents that really
#' are the parent, the criterion is a lower tail: the threshold at significance
#' `alpha` is the `alpha` quantile, and a candidate is accepted when its observed
#' LOD score is at least that large. Amiri Roudbar et al. (2025) use
#' `alpha = 0.05` and `alpha = 0.01`, so that 95% and 99% of simulated true
#' parents exceed the respective threshold.
#'
#' This is the opposite tail from the classical CERVUS criterion, which
#' thresholds the upper tail of a distribution generated from unrelated
#' candidates; see [delta_critical()] for that alternative.
#'
#' @param x A `"lod_null"` object from [lod_null()].
#' @param alpha Significance levels.
#' @param ... Ignored.
#'
#' @return A `data.frame` with columns `alpha`, `confidence` (`1 - alpha`) and
#'   `critical_lod`.
#'
#' @references
#' Amiri Roudbar, M., Mousavi, S.F., Akbarzadeh, M., Brounts, S.H. & Momen, M.
#' (2025) Pairwise paternity assignment with forward-backward simulations:
#' refining CERVUS using trio-based likelihood and locus-specific error rates.
#' \emph{Ecology and Evolution}, \strong{15}(10), e72230.
#' \doi{10.1002/ece3.72230}
#'
#' @examples
#' sim <- simulate_population(n = 30, n_loci = 8, n_alleles = 6, seed = 3)
#' p <- allele_freqs(sim$genotypes)
#' nd <- lod_null(sim$genotypes, offspring = sim$pedigree$offspring[1],
#'                freqs = p, error = 0.01, method = "backward", nsim = 500)
#' lod_critical(nd)
#' @export
lod_critical <- function(x, alpha = c(0.05, 0.01), ...) {
  stopifnot(inherits(x, "lod_null"))
  q <- stats::quantile(as.numeric(x), probs = alpha, names = FALSE, type = 7)
  data.frame(alpha = alpha, confidence = 1 - alpha, critical_lod = q)
}

#' @param x A `"lod_null"` object.
#' @param ... Ignored.
#' @rdname lod_null
#' @export
print.lod_null <- function(x, ...) {
  cat("<lod_null>", attr(x, "method"), "simulation,", attr(x, "nsim"),
      "replicates, type =", attr(x, "type"), "\n")
  cat("  simulated true-parent LOD: median ",
      format(stats::median(as.numeric(x)), digits = 4),
      ", 5th pct ", format(stats::quantile(as.numeric(x), 0.05, names = FALSE), digits = 4),
      ", 1st pct ", format(stats::quantile(as.numeric(x), 0.01, names = FALSE), digits = 4),
      "\n", sep = "")
  invisible(x)
}
